apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-quality
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wine-quality
  template:
    metadata:
      labels:
        app: wine-quality
    spec:
      containers:
      - name: wine-quality
        image: wine-quality:latest
        imagePullPolicy: Never
        ports:
